/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: number; petId: string }, { topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'Notification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: { name: string; photoUrl: string }; foodOrder?: { quantity: number } }, ApiResponse<200, { id: string; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: number; petId: string } }>
    'SlackLabelNotifier': EventHandler<{ issue: unknown; label: unknown; repository: unknown; priority: 'HIGH' | 'MEDIUM' | 'LOW' }, never>
    'IssueLabelStateUpdater': EventHandler<{ issue: { number: number; title: string; url: string; state: string }; label: { name: string; color: string }; repository: { name: string; fullName: string; url: string }; priority: 'HIGH' | 'MEDIUM' | 'LOW' }, { topic: 'issue-label-stored'; data: { issue: unknown; label: unknown; repository: unknown; priority: 'HIGH' | 'MEDIUM' | 'LOW' } }>
    'IssueLabelClassifier': EventHandler<{ issue: { number: number; title: string; url: string; state: string }; label: { name: string; color: string }; repository: { name: string; fullName: string; url: string } }, { topic: 'issue-label-classified'; data: { issue: { number: number; title: string; url: string; state: string }; label: { name: string; color: string }; repository: { name: string; fullName: string; url: string }; priority: 'HIGH' | 'MEDIUM' | 'LOW' } }>
    'IssueCommentNotifier': EventHandler<{ issue: { number: number; title: string; url: string }; comment: { body: string; author: string; url: string }; repository: { name: string; fullName: string } }, never>
    'GitHubWebhook': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'issue-label-received'; data: { issue: { number: number; title: string; url: string; state: string }; label: { name: string; color: string }; repository: { name: string; fullName: string; url: string } } } | { topic: 'issue-comment-received'; data: { issue: { number: number; title: string; url: string }; comment: { body: string; author: string; url: string }; repository: { name: string; fullName: string } } }>
  }
    
}