/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'WriteFixGuide': EventHandler<unknown, never>
    'ScanRepo': EventHandler<unknown, { topic: 'repo.scanned'; data: unknown }>
    'PickIssue': ApiRouteHandler<unknown, ApiResponse<200, unknown>, { topic: 'issue.selected'; data: unknown }>
    'GenerateFixGuide': EventHandler<unknown, { topic: 'fix-guide.generated'; data: unknown }>
    'FetchIssues': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown>, never>
    'FetchIssueDetails': EventHandler<unknown, { topic: 'issue.details.fetched'; data: unknown }>
    'AnalyzeIssue': EventHandler<unknown, { topic: 'issue.analyzed'; data: unknown }>
  }
    
}