/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GetReleaseNotes': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, unknown>, never>
    'GenerateReleaseNotesOutput': EventHandler<unknown, never>
    'AnalyzeCommitsWithAI': EventHandler<unknown, { topic: 'release.generate-notes'; data: unknown }>
    'FetchGitHubCommits': EventHandler<unknown, { topic: 'release.analyze-commits'; data: unknown }>
    'GenerateReleaseNotes': ApiRouteHandler<unknown, ApiResponse<202, unknown> | ApiResponse<400, unknown>, { topic: 'release.fetch-commits'; data: unknown }>
  }
    
}