/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: number; petId: string }, { topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'Notification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: { name: string; photoUrl: string }; foodOrder?: { quantity: number } }, ApiResponse<200, { id: string; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: number; petId: string } }>
    'GitHubWebhook': ApiRouteHandler<{ action: string; release: { name: string; body: string | unknown; html_url: string; tag_name: string; published_at: string; author?: { login: string; avatar_url: string } }; repository: { name: string; full_name: string; html_url: string } }, ApiResponse<200, { action: string }>, { topic: 'github-release-published'; data: { releaseName: string; releaseBody: string; releaseUrl: string; releaseTag: string; publishedAt: string; repositoryName: string; repositoryUrl: string; authorLogin?: string } }>
    'DiscordNotification': EventHandler<{ releaseName: string; releaseBody: string; releaseUrl: string; releaseTag: string; publishedAt: string; repositoryName: string; repositoryUrl: string; authorLogin?: string }, never>
  }
    
}